[package]
name = "omni_engine"
version = "2.1.0"
edition = "2021"
authors = ["Omni AI Team"]
description = "Sovereign In-Process AI Engine with Causal KV-Cache Manipulation, Sandbox Isolation & Multi-Agent Swarm"

[lib]
name = "omni_engine"
path = "src/lib.rs"

[[bin]]
name = "omni_engine"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
tower-http = { version = "0.5", features = ["cors", "fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "stream", "blocking"] }
futures-util = "0.3"
async-stream = "0.3"
uuid = { version = "1.8", features = ["v4", "serde"] }
rand = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mime_guess = "2.0"
colored = "2.1"
indicatif = "0.17"
mlua = { version = "0.9", features = ["lua54", "vendored"] }
parking_lot = "0.12"
libloading = "0.8"
flate2 = "1.0"
tempfile = "3"
ratatui = "0.30.2"
crossterm = "0.29.0"
tui-input = "0.15.5"
dirs = "7.0.0"
chrono = "0.4.45"
arboard = "3.6.1"


[build-dependencies]
cc = "1.0"
